export interface Velatorio {
  administrador: string,
  capillas: number,
  cveAsignacion: number,
  cveCp: number,
  desCalle: string,
  desColonia: string,
  desDelegacion: string,
  desEstado: string,
  desMunicipio: string,
  estatus: boolean,
  idCodigoPostal: number,
  idCp: number,
  idDelegacion: number,
  idVelatorio: number,
  nomRespoSanitario: string,
  nomVelatorio: string,
  numExterior: number,
  numTelefono: number,
  salasCremacion: number,
  salasEmbalsamamiento: number
}
